#!/bin/sh
# /etc/init.d/S99aesdsocket script wrapper for Buildroot platform integration

DAEMON="aesdsocket"
BINARY="/usr/bin/aesdsocket"
PIDFILE="/var/run/aesdsocket.pid"

case "$1" in
    start)
        echo -n "Starting daemon: $DAEMON... "
        start-stop-daemon --start --quiet --oknodo --exec $BINARY -- -d
        if [ $? -eq 0 ]; then
            echo "OK"
        else
            echo "FAIL"
        fi
        ;;
    stop)
        echo -n "Stopping daemon: $DAEMON... "
        start-stop-daemon --stop --quiet --oknodo --retry TERM/5/KILL/5 --exec $BINARY
        if [ $? -eq 0 ]; then
            echo "OK"
        else
            echo "FAIL"
        fi
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
